import Head from "next/head";
import { BsFillMoonStarsFill, BsFillSunFill } from "react-icons/bs";
import { SiGmail } from "react-icons/si";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import cloud from "../public/cloudicon.png";
import swdev from "../public/swdevicon.png";
import Image from "next/image";
import ben from "../public/ben.png";
import asp from "../public/aspnet.jpg";
import reactlogo from "../public/reactlogo.png";
import msslogo from "../public/mss.png";
import aws from "../public/aws.png";
import terraform from "../public/terrafrom.png";
import k8 from "../public/k8.png";
import jenkins from "../public/jenkins.png";
import ansible from "../public/ansible.png";
import docker from "../public/docker.png";
import postman from "../public/postman.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  false;
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Benjamin Xiong Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">
              developedbyben
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  className={
                    darkMode
                      ? "hidden cursor-pointer text-2xl"
                      : "cursor-pointer text-2xl"
                  }
                  onClick={() => setDarkMode(!darkMode)}
                />
                <BsFillSunFill
                  className={
                    !darkMode
                      ? "hidden cursor-pointer text-2xl"
                      : "cursor-pointer text-2xl dark:text-white"
                  }
                  onClick={() => setDarkMode(!darkMode)}
                />
              </li>
              <li>
                <a
                  className="bg-teal-600 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Benjamin Xiong
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Software Developer | Cloud Engineer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white">
              Providing cloud and software solutions. Get in contact with me
              below.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillTwitterCircle className="cursor-pointer" />
            <AiFillLinkedin className="cursor-pointer" />
            <AiFillGithub className="cursor-pointer" />
            <SiGmail className="cursor-pointer" />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image classNames="" src={ben} layout="fill" objectFit="cover" />
          </div>
        </section>
        <section>
          <div className="text-center p-10">
            <h3 className="text-3xl py-1 dark:text-white">About Me</h3>
            <p className="dark:text-white">
              I am an aspiring engineer looking to bring an unwavering work
              ethic, can-do attitude, and add value to the team. I've been
              coding since January 2021 and have interests in Real Estate,
              Insurance, FinTech, Blockchain, and Cloud. When I'm not pursuing
              my dreams, I like to watch football, basketball, eSports, and
              spend time with my two boys.
            </p>
            <div className=""></div>
          </div>
          <div className="lg:flex-wrap gap-10">
            <div className="text-center shadow-xl p-10 rounded-xl my-10 dark:bg-white">
              <Image src={cloud} width={200} height={200} />
              <h2 className="py-4 text-xl text-teal-600 font-medium">
                Cloud Design
              </h2>
              <p>
                Architect, deploy, and monitor software applications on new or
                existing AWS cloud infrastructure
              </p>
              <h4 className="py-4">Tools I use</h4>
              <div className="grid grid-cols-3 gap-5 lg:grid-cols-6">
                <Image
                  className="object-scale-down"
                  src={aws}
                  width={125}
                  height={80}
                />
                <Image
                  className="object-scale-down"
                  src={terraform}
                  width={75}
                  height={75}
                />
                <Image
                  className="object-scale-down"
                  src={k8}
                  width={175}
                  height={100}
                ></Image>
                <Image
                  className="object-scale-down"
                  src={jenkins}
                  width={130}
                  height={80}
                />
                <Image
                  className="object-scale-down"
                  src={ansible}
                  width={50}
                  height={50}
                />
                <Image
                  className="object-scale-down"
                  src={docker}
                  width={75}
                  height={75}
                />
              </div>
            </div>
            <div className="text-center shadow-xl p-10 rounded-xl my-10 dark:bg-white">
              <Image src={swdev} />
              <h3 className="text-xl py-4 text-teal-600 font-medium">
                Software Development
              </h3>
              <p></p>
              <h4
                className="py-4
              "
              >
                Tools I use
              </h4>
              <div className="grid grid-cols-2 gap-5 lg:grid-cols-4">
                <Image
                  className="object-scale-down"
                  src={reactlogo}
                  width={50}
                  height={100}
                />
                <Image
                  className="object-scale-down"
                  src={asp}
                  width={50}
                  height={50}
                />
                <Image
                  className="object-scale-down"
                  src={postman}
                  width={70}
                  height={50}
                />
                <Image
                  className="object-scale-down"
                  src={msslogo}
                  width={70}
                  height={60}
                />
              </div>
            </div>
          </div>
        </section>
        <section>
          <div className="text-center shadow-xl p-10 rounded-xl my-10">
            <h3 className="text-3xl py-1 dark: text-white">Portfolio</h3>
            <p className="dark:text-white">Under Construction</p>
          </div>
        </section>
      </main>
    </div>
  );
}
